version: "3.9"
services:
  frontend:
    image: rahulrai9/frontend-app:${FRONTEND_IMAGE_TAG:-latest}
    container_name: frontend-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - nodeapp-nw
    depends_on:
      - backend

  backend:
    image: rahulrai9/backend-app:${BACKEND_IMAGE_TAG:-latest}
    container_name: backend-app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - MONGO_URL=mongodb://mongo:27017/mydb
    networks:
      - nodeapp-nw
    depends_on:
      - db

  db:
    image: mongo:6
    container_name: mongo
    restart: unless-stopped
    networks:
      - nodeapp-nw
    volumes:
      - mongo-data:/data/db

networks:
  nodeapp-nw:
    driver: bridge

volumes:
  mongo-data:
